require:
  - rubocop-minitest
  - rubocop-disable_syntax

AllCops:
  TargetRubyVersion: 2.7
  NewCops: enable
  SuggestExtensions: false

Style/StringLiterals:
  EnforcedStyle: double_quotes

Style/RescueModifier:
  Exclude:
    - test/**/*

Style/IfUnlessModifier:
  Enabled: false

Style/SymbolArray:
  EnforcedStyle: brackets

Style/WordArray:
  EnforcedStyle: brackets

Style/GuardClause:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/MutableConstant:
  Enabled: false

Style/MissingRespondToMissing:
  Enabled: false

Style/TrailingCommaInHashLiteral:
  EnforcedStyleForMultiline: comma

Style/TrailingCommaInArrayLiteral:
  EnforcedStyleForMultiline: comma

Style/NumericPredicate:
  Enabled: false

Style/NegatedIf:
  Enabled: false

Style/ConditionalAssignment:
  Enabled: false

Style/SafeNavigation:
  Enabled: false

Style/NumericLiterals:
  Enabled: false

Style/Next:
  Enabled: false

Style/GlobalVars:
  Exclude:
    - test/**/*

Style/Lambda:
  EnforcedStyle: literal

Style/WhileUntilModifier:
  Enabled: false

Style/HashAsLastArrayItem:
  Enabled: false

Style/MapToHash:
  Enabled: true

Style/FetchEnvVar:
  Enabled: false

Style/DisableSyntax:
  DisableSyntax:
    - unless
    - safe_navigation
    - endless_methods
    - arguments_forwarding
    - numbered_parameters
    - pattern_matching
    - shorthand_hash_syntax
    - and_or_not
    - until
    - percent_literals

Lint/MissingSuper:
  Enabled: false

Layout/EmptyLinesAroundAccessModifier:
  EnforcedStyle: only_before

Layout/IndentationConsistency:
  EnforcedStyle: indented_internal_methods

Layout/ArgumentAlignment:
  Enabled: false

Layout/LineLength:
  Enabled: false

Layout/MultilineMethodCallIndentation:
  Enabled: false

Layout/HashAlignment:
  Enabled: false

Naming/FileName:
  ExpectMatchingDefinition: true
  CheckDefinitionPathHierarchy: false
  Exclude:
    - lib/online_migrations/version.rb
    - test/support/schema.rb
    - test/support/db/**
    - test/test_helper.rb
    - gemfiles/**.gemfile

Naming/VariableNumber:
  Exclude:
    - test/**/*

Naming/MethodParameterName:
  AllowedNames:
    - of
    - fk

Naming/AccessorMethodName:
  Exclude:
    - test/**/*

Gemspec/RequiredRubyVersion:
  Enabled: false

Gemspec/RequireMFA:
  Enabled: false

Bundler/OrderedGems:
  Enabled: false

Metrics:
  Enabled: false

Minitest/MultipleAssertions:
  Enabled: false

Minitest/RefuteFalse:
  Enabled: false

Minitest/AssertPredicate:
  Enabled: false

Minitest/EmptyLineBeforeAssertionMethods:
  Enabled: false
